config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  resource :asset_pair_import, only: %i[new create destroy]
  resources :asset_pairs, only: %i[index show] do
    resources :durations, only: [] do
      resources :chart_ticks, only: %i[index], defaults: { format: :json }
    end
  end
  resources :backtests, only: %i[index show]
  resources :reset_backtests, only: :create

  root 'dashboards#show'

  mount MissionControl::Jobs::Engine, at: '/jobs'
end

app/models/backtest.rb
# frozen_string_literal: true

class Backtest < ApplicationRecord
  include DurationConcern

  BACKTEST_FUND = 10_000

  belongs_to :asset_pair

  has_many :smoothed_trends, foreign_key: %i[asset_pair_id iso8601_duration],
                             dependent: nil, inverse_of: false
  has_many :backtest_trades, -> { order(range_position: :desc) },
           foreign_key: %i[asset_pair_id iso8601_duration],
           dependent: :destroy,
           inverse_of: :backtest

  before_create do
    self.usd_volume    = BACKTEST_FUND
    self.current_value = BACKTEST_FUND
  end

  def new_smoothed_trends = smoothed_trends.where(range_position: next_range_position..)
  def percentage_change = (current_value - BACKTEST_FUND) / BACKTEST_FUND * 100

  private

  def next_range_position = last_range_position + 1
end

app/controllers/backtests_controller.rb
# frozen_string_literal: true

class BacktestsController < ApplicationController
  def index
    @backtests = Backtest.joins(:asset_pair)
                         .merge(AssetPair.importing)
                         .order(current_value: :desc)
  end

  def show
    @backtest = Backtest.includes(:backtest_trades).find(params.extract_value(:id))
  end
end

app/views/backtests/index.html.erb
<%= button_to 'Reset all backtests', reset_backtests_path %>

<% @backtests.each.with_index(1) do |backtest, index| %>
  <p>Rank: <%= index -%> <%= backtest.asset_pair.name -%> (<%= duration_to_timeframe(backtest.duration) -%>) - <%= number_to_currency(backtest.current_value) %> (<%= number_to_percentage(backtest.percentage_change) %>)</p>
<% end %>

app/views/backtests/show.html.erb
<%= turbo_frame_tag dom_id(@backtest) do %>
  <header>Backtest</header>
  <table>
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Action</th>
        <th scope="col">Volume</th>
        <th scope="col">Price</th>
        <th scope="col">Fee</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <% @backtest.backtest_trades.each do |backtest_trade| %>
        <tr>
          <td><%= l(backtest_trade.range.first, format: :table) %></td>
          <td><%= backtest_trade.action.to_s.upcase %></td>
          <td><%= number_with_delimiter(backtest_trade.volume) %></td>
          <td><%= number_to_currency(backtest_trade.price) %></td>
          <td><%= number_to_currency(backtest_trade.fee) %></td>
          <td><%= number_to_currency(backtest_trade.value) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>