config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  resource :asset_pair_import, only: %i[new create destroy]
  resources :asset_pairs, only: %i[index show] do
    resources :durations, only: [] do
      resources :chart_ticks, only: %i[index], defaults: { format: :json }
    end
  end
  resources :backtests, only: %i[index show]
  resources :reset_backtests, only: :create

  root 'dashboards#show'

  mount MissionControl::Jobs::Engine, at: '/jobs'
end

app/models/asset_pair.rb
# frozen_string_literal: true

class AssetPair < ApplicationRecord
  has_many :trades, dependent: :restrict_with_error
  has_many :backtests, dependent: :destroy

  after_create :create_backtests

  scope :importing, -> { where(importing: true) }
  scope :pending, -> { where(importing: false) }
  scope :usd, -> { where(quote: 'ZUSD') }
  scope :missing_on_exchange, -> { where.not(missing_on_exchange_at: nil) }

  def missing_on_exchange? = missing_on_exchange_at.present?

  def import = update!(importing: true)
  def disable_import = update!(importing: false)

  def reset_backtests
    ActiveRecord::Base.transaction do
      backtests.destroy_all
      create_backtests
    end
  end

  private

  def create_backtests
    Ohlc.durations.each do |duration|
      Backtest.create!(
        asset_pair: self,
        duration:
      )
    end
  end
end

app/controllers/asset_pairs/charts_controller.rb
# frozen_string_literal: true

module AssetPairs
  class ChartsController < ApplicationController
    def show
      @asset_pair = AssetPair.find(params[:asset_pair_id])
      @duration = params[:id]
    end
  end
end

app/controllers/asset_pairs_controller.rb
# frozen_string_literal: true

class AssetPairsController < ApplicationController
  def index
    @asset_pairs = AssetPair.importing.order(:name)
  end

  def show
    @asset_pair = AssetPair.find(params[:id])
    @duration = ActiveSupport::Duration.parse(params[:iso8601_duration] || 'P1D')
    @backtest = Backtest.find([params[:id], @duration.iso8601])
  end
end

app/views/asset_pairs/index.html.erb
<h1>Asset pairs</h1>

<article class="component">
  <%= link_to 'Import Asset Pair', new_asset_pair_import_path %>

  <table id="asset-pairs">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">???</th>
        <th scope="col">???</th>
      </tr>
    </thead>
    <tbody>
      <% @asset_pairs.each do |asset_pair| %>
        <tr>
          <th scope="row"><%= link_to asset_pair.name, asset_pair_path(asset_pair) -%></th>
          <td>
            <% if asset_pair.missing_on_exchange? %>
              Missing on exchange
            <% else %>
              Active
            <% end %>
          </td>
          <td>???</td>
          <td>???</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</article>

app/views/asset_pairs/show.html.erb
<%= render 'breadcrumbs', crumbs: [
      link_to('Asset Pairs', asset_pairs_path),
      @asset_pair.name
    ] %>

<%= tag.h1 @asset_pair.name %>

<nav>
  <details class="dropdown">
    <summary>
      <%= duration_to_timeframe(@duration) %>
    </summary>
    <ul dir="rtl">
      <% Ohlc.durations.each do |duration| %>
        <li>
          <%= link_to(
                duration_to_timeframe(duration),
                asset_pair_path(
                  @asset_pair,
                  iso8601_duration: duration.iso8601
                )
              ) %>
        </li>
      <% end %>
    </ul>
  </details>
</nav>

<%= tag.div class: 'asset-pair-chart-component',
            data: {
              controller: 'asset-pair-chart-component',
              asset_pair_chart_component_price_format_value: {
                type: 'price',
                precision: @asset_pair.cost_decimals,
                minMove: 1.0 / (10**@asset_pair.cost_decimals)
              },
              asset_pair_chart_component_chart_ticks_url_value: asset_pair_duration_chart_ticks_url(
                @asset_pair,
                @duration.iso8601
              )
            } %>

<article>
  <%= button_to 'Stop tracking', asset_pair_import_path, params: { asset_pair_id: @asset_pair.id }, method: :delete %>
</article>

<article>
  <%= turbo_frame_tag dom_id(@backtest), src: backtest_path(@backtest), loading: 'lazy' %>
</article>